#! /bin/bash
#
# setup -- prepare a new presentation
#
if [ $# -lt 2 ]
then
	echo "not enough arguments"
	echo "usage:"
	echo "./setup <name> <number>"
	exit 1
fi

presentation=${1}
number=${2}
directory=${number}_${presentation}

mkdir ${directory}

cp 00_template/common.tex ${directory}
cp 00_template/slides.tex ${directory}
cp 00_template/handout.tex \
	${directory}/${presentation}-handout.tex
cp 00_template/presentation.tex \
	${directory}/SeminarKlima-${number}-${presentation}-presentation.tex

sed -e "s/xxx/${presentation}/g" -e "s/yyy/${number}/g" 00_template/Makefile > ${directory}/Makefile

