#
# Makefile -- images for chapter 4
#
# (c) 2018 Prof Dr Andreas Müller, Hochschule Rapperswil
#
IMAGES = boxmodell.pdf

all:	images

images:	$(IMAGES)


boxmodell.pdf:	boxmodell.tex
	pdflatex boxmodell.tex

