#
# Makefile -- process images
#
# (c) 2018 Prof Dr Andreas Müller, Hochschule Rapperswil
#
images =								\
	3b1f-skript.eps							\
	3b1f-skript-klimawandel.eps					\
	graph_salinity.eps						\
	graph_temp.eps							\
	result-3b2f-script.eps

pdf =									\
	3b1f-skript.pdf							\
	3b1f-skript-klimawandel.pdf					\
	graph_salinity.pdf						\
	graph_temp.pdf							\
	result-3b2f-script.pdf

all:	$(pdf)

$(pdf):	$(images)
	bash bbfix
	
