#
# Makefile -- xxx
#
# (c) 2018 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	xxx-handout.pdf SeminarKlima-yyy-xxx-presentation.pdf

SOURCES = common.tex slides.tex

SeminarKlima-yyy-xxx-presentation.pdf:	SeminarKlima-yyy-xxx-presentation.tex $(SOURCES)
	pdflatex SeminarKlima-yyy-xxx-presentation.tex

xxx-handout.pdf:	xxx-handout.tex $(SOURCES)
	pdflatex xxx-handout.tex

