#
# Makefile -- xxx
#
# (c) 2017 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	xxx-handout.pdf xxx-presentation.pdf

SOURCES = common.tex xxx.tex

xxx-presentation.pdf:	xxx-presentation.tex $(SOURCES)
	pdflatex xxx-presentation.tex

xxx-handout.pdf:	xxx-handout.tex $(SOURCES)
	pdflatex xxx-handout.tex

