#
# Makefile
#
# (c) 2018 Prof Dr Andreas Müller, Hochschule Rapperswil
#
all:	pitchfork.pdf saddle-node.pdf lin1.pdf trans.pdf kubisch.pdf

pitchfork.pdf:	pitchfork.tex
	pdflatex pitchfork.tex

saddle-node.pdf:	saddle-node.tex
	pdflatex saddle-node.tex

lin1.pdf:	lin1.tex
	pdflatex lin1.tex

trans.pdf:	trans.tex
	pdflatex trans.tex

kubisch.pdf:	kubisch.tex
	pdflatex kubisch.tex
